name: My lastest blogs from anhkolamgidauanhthe.me
on:
  # Schedule weekly updates
  schedule: [{cron: "0 0 * * 0"}]
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.rss.svg
  token: NOT_NEEDED
  base: ""
  plugin_rss: yes
  plugin_rss_source: https://www.anhkolamgidauanhthe.me/rss
  plugin_rss_limit: 5
